# Generated by Django 3.0.8 on 2020-07-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledevents',
            name='attendance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_events', to='classroom.Attendance'),
        ),
    ]
