# Generated by Django 3.0.8 on 2020-07-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200719_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledevents',
            name='attendance',
        ),
    ]
