# Generated by Django 3.0.8 on 2020-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_remove_enrolledevents_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledevents',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
