# Generated by Django 3.0.8 on 2020-07-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200719_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledevents',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
