# Generated by Django 3.0.8 on 2020-07-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20200720_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledevents',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
