# Generated by Django 3.0.8 on 2020-08-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20200813_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledevents',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
