# Generated by Django 3.0.8 on 2020-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20200813_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledevents',
            name='certificate',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
