# Generated by Django 3.0.8 on 2020-08-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_auto_20200818_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Add Video for your event.'),
        ),
    ]
