# Generated by Django 3.0.8 on 2020-08-19 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_event_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='videofile',
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(default=datetime.datetime(2020, 8, 19, 13, 37, 30, 714483, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time of Event'),
        ),
    ]
