# Generated by Django 3.0.8 on 2020-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_auto_20200819_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Poster'),
        ),
    ]
