# Generated by Django 3.0.8 on 2020-08-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20200820_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='event',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
